outputFile: "file_contents.txt"
useGitignore: true

defaultExcludePatterns:
  - ".git/**"
  - "node_modules/**"
  - ".cursor/**"
  - ".vscode/**"
  - ".taskmaster/**"
  - ".env"
  - ".env.example"
  - "*.lock"
  - "**/file_context.txt"
  - "**/diff.txt"
  - "docs/**"
  - "cluster"
  - "scripts"
  - "go.sum"
  - ".gitignore"
  - ".golangci.yml"
  - ".editorconfig"
  - ".merge_files.yaml"
  - ".pre-commit-config.yaml"
  - ".prettierignore"
  - ".prettierrc.toml"
  - ".yamlfix.toml"
